language: swift

matrix:
    include:
        - os: linux
          sudo: required
          language: c++
        - os: osx
          osx_image: xcode8.3
          sudo: required
          language: objective-c

script:
    - swift build
    - swift test

before_install:
    - chmod ugo+x ./Scripts/InstallSwift.sh
    - . ./Scripts/InstallSwift.sh

notifications:
    email:
        on_success: never
        on_failure: change